spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:postsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:schema.sql
